feat: getmap implementation
MapColonies/exporter-trigger pull request #145
Opened 2021-08-03 06:26 UTC by AnguIar

2021-08-03 11:02 UTC, asafMasa requested changes
add integration test
add unit test's

2021-08-03 11:02 UTC, asafMasa commented on src/controllers/gmController.ts
> +      const layer = (
add log before

2021-08-03 12:36 UTC, AnguIar commented on docs/openapi3.yaml
> +          description: The maximum zoom level in which the tiles will be created
Given user input is zoom level, isn't it?

2021-08-03 12:44 UTC, AnguIar commented on src/controllers/gmController.ts
> +      const layer = (
There is a log before the main part - inside jobManagerClient.ts

2021-08-03 15:46 UTC, asafMasa requested changes

2021-08-03 15:46 UTC, asafMasa commented on docs/openapi3.yaml
> +          description: The target resolution in which the tiles will be created - DEGREES FOR PIXEL!
degree to pixel, no need for the exclamation remark "!"

2021-08-03 15:46 UTC, asafMasa commented on docs/openapi3.yaml
> +          maximum: 1000
1000 is the default, no?

2021-08-03 15:46 UTC, asafMasa commented on src/clients/jobManagerClient.ts
> +    const resourceId = data.cswLayerId + '-' + data.version;
why?
use the productId from the catalog

2021-08-03 15:46 UTC, asafMasa commented on src/util/utils.ts
> +    return Math.floor(Math.log2(180 / (resolution * 256)));
this calculation is wrong
if the resolution is between 7-8 i expect to create 8, instead it creates 7 for example:

Math.floor(Math.log2(180 / (0.00274658203125 * 256))); -> 8

Math.floor(Math.log2(180 / (0.00274659203125 * 256))); -> expected 8 actual 7

2021-08-03 15:46 UTC, asafMasa commented on src/util/utils.ts
> +    return Math.floor(Math.log2(180 / (resolution * 256)));
add unit test for this logic, use this as reference -> 
https://github.com/MapColonies/discrete-overseer-creator/blob/master/tests/unit/utils/zoomToResulation.spec.ts

2021-08-03 16:07 UTC, asafMasa requested changes

2021-08-03 16:07 UTC, asafMasa commented on src/clients/jobManagerClient.ts
> +    const resourceId = data.cswProductId + '-' + data.version;
const resourceId = data.cswProductId;
no need for "+ '-' + data.version;"

2021-08-04 08:36 UTC, asafMasa approved these changes

2021-08-04 12:25 UTC, merged