chore auth support WIP
MapColonies/exporter-trigger pull request #26
Opened 2022-08-01 13:16 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-08-01 14:05 UTC, CL-SHLOMIKONCHA approved these changes

2022-08-02 09:13 UTC, asafMasa requested changes
👍

2022-08-02 09:13 UTC, asafMasa commented on helm/config/envoy.yaml
> +                      metadata_context_namespaces:
check what relevant

2022-08-02 09:13 UTC, asafMasa commented on helm/values.yaml
> +  tag: 'v2.2.0'
latest

2022-08-02 09:13 UTC, asafMasa commented on helm/values.yaml
> +    enabled: true
resources isn't config?

2022-08-02 09:13 UTC, asafMasa commented on helm/values.yaml
> +    enabled: true
resources isn't config?

2022-08-02 13:58 UTC, cl-shaharshavit-rnd commented on helm/values.yaml
> +    enabled: true
this is the config!

2022-08-03 09:17 UTC, asafMasa approved these changes

2022-08-03 09:19 UTC, merged