feat: first commit for new cleanup managment logic
MapColonies/exporter-trigger pull request #56
Opened 2023-03-09 08:05 UTC by ronenkapelian

Generic cleanupData

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✔                                                                      |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                     |

As we would like to reuse exporter-clean as generic cleanup tool for jobs on jobManager, we would like create dedicated object in params that responsible for "what" and "when" to delete

2023-03-09 10:01 UTC, asafMasa requested changes
👍 good job

2023-03-09 10:01 UTC, asafMasa commented on src/clients/jobManagerWrapper.ts
> +      const oldExpirationDate = new Date(job.parameters.cleanupData?.cleanupExpirationTime as Date);
don't we need to check if cleanupExpirationTime exists before comepring it?

2023-03-09 10:01 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +    const cleanupData: ICleanupData = {
consider refactor this lines to a method and use it from finalize methods

2023-03-09 10:01 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +    const cleanupData: ICleanupData = {
consider refactor this lines to a method and use it from finalize methods

2023-03-09 11:07 UTC, ronenkapelian commented on src/clients/jobManagerWrapper.ts
> +      const oldExpirationDate = new Date(job.parameters.cleanupData?.cleanupExpirationTime as Date);
i think no, becouse it will happen only on case of updating completed job, completed job always come after finilize that generating this object

2023-03-09 11:44 UTC, ronenkapelian commented on src/tasks/models/tasksManager.ts
> +    const cleanupData: ICleanupData = {
done

2023-03-09 11:44 UTC, ronenkapelian commented on src/tasks/models/tasksManager.ts
> +    const cleanupData: ICleanupData = {
done

2023-03-09 13:45 UTC, asafMasa approved these changes
💯

2023-03-12 08:43 UTC, asafMasa approved these changes

2023-03-12 09:40 UTC, merged