chore: revert batching algorithm
MapColonies/exporter-trigger pull request #57
Opened 2023-03-13 12:35 UTC by shimoncohen

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2023-03-13 12:50 UTC, asafMasa requested changes

2023-03-13 12:50 UTC, asafMasa commented on src/createPackage/models/createPackageManager.ts
> +      const recordBatches = bboxToTileRange(record.sanitizedBox as BBox2d, record.zoomLevel);
fix all zoom levels for each feature

2023-03-13 13:36 UTC, shimoncohen commented on src/createPackage/models/createPackageManager.ts
> +      const recordBatches = bboxToTileRange(record.sanitizedBox as BBox2d, record.zoomLevel);
Fixed.

2023-03-13 13:40 UTC, ronenkapelian commented on src/createPackage/models/createPackageManager.ts
> +        console.log(recordBatches);
remove console.log

2023-03-13 13:43 UTC, ronenkapelian commented on tests/integration/createPackage/createExportPackage.spec.ts
> +      // generateTileGroupsSpy.mockReturnValue([]);
add comment of "todo-after bug fix it will be returned..."etc...

2023-03-13 14:02 UTC, ronenkapelian requested changes
run local + local docker on azure and validate creation of valid gpkg in getMap API and ROI api

2023-03-13 15:16 UTC, asafMasa requested changes
👍

2023-03-15 08:04 UTC, ronenkapelian approved these changes

2023-03-15 10:18 UTC, asafMasa approved these changes

2023-03-15 10:19 UTC, merged