feat: Remove deprecation (MAPCO-4117)
MapColonies/exporter-trigger pull request #90
Opened 2024-03-18 16:11 UTC by razbroc

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✔                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

Related issues: #MAPCO-4117

2024-03-21 10:10 UTC, asafMasa requested changes

2024-03-21 10:10 UTC, asafMasa commented on src/clients/jobManagerWrapper.ts
> +  //TODO: once will be only one kind of exported jobs, no need to filter by ROI's
please open an issue

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> - */
why was this decorator deleted but the object remained? Do we still need th ICreatePackage? can it be removed?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> -}
why do we still need the ICallbackBase? can it be removed?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> -export interface IWorkerInput extends IWorkerInputBase {
why do we still need the "IWorkerInputBase"? can it be removed?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> -
do we still need the "ICallbackDataExportBase"?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> - */
Do we still need th IBaseCreatePackage ? can it be removed?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> - */
why do we still need this object? isn't IJobExportParameters enough?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> -/**
why do we still need "IInput" interface?

2024-03-21 10:10 UTC, asafMasa commented on src/common/interfaces.ts
> -/**
Please remove the "ExportVersion" enum as we only use the "ROI" scenario

2024-03-21 10:10 UTC, asafMasa commented on src/createPackage/models/createPackageManager.ts
> -  private generateTileGroups(polygon: Polygon | MultiPolygon, footprint: Polygon | MultiPolygon, zoom: number): ITileRange[] {
please revert its deletion and put in comment, add:
// TODO: remove and replace with `generateTileGroups` that is commented, when multiple tasks for GPKG target is possible

2024-03-21 10:10 UTC, asafMasa commented on src/finalizationManager.ts
>    private async handleROIJobs(): Promise<boolean> {
rename to handleExportJobs

2024-03-25 11:32 UTC, razbroc commented on src/clients/jobManagerWrapper.ts
> +  //TODO: once will be only one kind of exported jobs, no need to filter by ROI's
https://mapcolonies.atlassian.net/browse/MAPCO-4129

2024-03-25 11:47 UTC, razbroc commented on src/common/interfaces.ts
> - */
removed it all

2024-03-25 11:49 UTC, razbroc commented on src/common/interfaces.ts
> -}
removed

2024-03-25 11:52 UTC, razbroc commented on src/common/interfaces.ts
> -export interface IWorkerInput extends IWorkerInputBase {
removed

2024-03-25 11:54 UTC, razbroc commented on src/common/interfaces.ts
> -
we still need it. it is used for example in `sendExportCallbacks` and more.

2024-03-25 11:56 UTC, razbroc commented on src/common/interfaces.ts
> - */
removed

2024-03-25 11:56 UTC, razbroc commented on src/common/interfaces.ts
> -/**
removed

2024-03-25 11:58 UTC, razbroc commented on src/common/interfaces.ts
> -/**
do you want me to keep the enum, for future possible versions? Or remove it and hard code `ROI`/remove the choosing possibility?

2024-03-25 11:59 UTC, razbroc commented on src/finalizationManager.ts
>    private async handleROIJobs(): Promise<boolean> {
fixed

2024-03-26 13:41 UTC, razbroc commented on src/createPackage/models/createPackageManager.ts
> -  private generateTileGroups(polygon: Polygon | MultiPolygon, footprint: Polygon | MultiPolygon, zoom: number): ITileRange[] {
fixed

2024-03-28 12:07 UTC, asafMasa commented on src/common/interfaces.ts
> -
please remove the base and leave only the ICallbackExportData as we don't need the base anymore

2024-03-28 12:09 UTC, asafMasa commented on src/common/interfaces.ts
> -/**
remove Completely

2024-03-31 07:43 UTC, razbroc commented on src/common/interfaces.ts
> -/**
fixed

2024-03-31 12:08 UTC, razbroc commented on src/common/interfaces.ts
> -
fixed

2024-05-13 12:13 UTC, asafMasa requested changes

2024-05-13 12:13 UTC, asafMasa commented on src/createPackage/models/createPackageManager.ts
> +// import { TileRanger } from '@map-colonies/mc-utils';
remove

2024-05-15 06:39 UTC, razbroc commented on src/createPackage/models/createPackageManager.ts
> +// import { TileRanger } from '@map-colonies/mc-utils';
fixed

2024-05-15 08:56 UTC, asafMasa approved these changes

2024-05-23 15:50 UTC, merged