refactor: change jobManagement to new jobDefentions (MAPCO-5091)
MapColonies/exporter-trigger pull request #98
Opened 2024-10-30 13:51 UTC by razbroc

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

Related issues: MAPCO-5091

2024-10-30 15:31 UTC, CL-SHLOMIKONCHA requested changes
You didnt change the `default.json` config file..

2024-10-30 15:31 UTC, CL-SHLOMIKONCHA commented on config/custom-environment-variables.json
> +    "jobDefinitions": {
move outside the `server` scope

2024-10-30 15:31 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
- add `jobDefinitions: {}` to global scope.
- add `domain: ' '` to global scope.

2024-10-30 16:10 UTC, razbroc commented on helm/values.yaml
ok

2024-10-30 16:11 UTC, razbroc commented on config/custom-environment-variables.json
> +    "jobDefinitions": {
ok

2024-10-31 08:31 UTC, CL-SHLOMIKONCHA approved these changes

2024-10-31 08:41 UTC, RonitKissis approved these changes

2024-10-31 08:42 UTC, merged